### ISSUE TITLE
is dependency on MuJoCo key necessary?

### ISSUE THREAD

**Issue by divideby2** [sisl/AdaptiveStressTestingToolbox#13]
Garage software install requires MuJoCo key which is free for a month and subsequently requires a paid license. If MuJoCo is not being used in AST, then an alternative can be provided.

**Comment by ancorso** [comment]
Hello!

Please take a look at our travis.yml to see how to install AST without a MuJoCo key. I've copied the relevant sections below. I will leave this issue open until we have a setup process in the documentation that describes this in detail.

  # Install garage and dependencies
  - cd Toolbox/garage
  - touch mjkey.txt
  - echo "hello" > mjkey.txt
  - ./scripts/setup_linux.sh --mjkey mjkey.txt --modify-bashrc
  - rm mjkey.txt
  - source ~/miniconda2/bin/activate garage

  # Run AST setup
  - cd ../../
  - source setup.sh
