### ISSUE TITLE
example ast mcts code has no collisions

### ISSUE THREAD

**Issue by divideby2** [sisl/AdaptiveStressTestingToolbox#14]
I wrote some code to compare performance of AST with random sampling and found no collisions with AST. My code is attached
[code.zip](https://github.com/sisl/AdaptiveStressTestingToolbox/files/2866852/code.zip)

**Comment by ancorso** [comment]
Thanks for the comments!
@mark-koren -- will you take a look at the MCTS performance on the AV problem next time you are getting data?

**Comment by mark-koren** [comment]
The Toolbox has undergone massive changes since this was opened. I am closing this topic, but let me know if this is still an issue.
