### ISSUE TITLE
What version of garage?

### ISSUE THREAD

**Issue by chelseas** [sisl/AdaptiveStressTestingToolbox#33]
I am trying to use this with the latest version of garage but it seems to be the wrong version. E.g. if I try to run ControlPolicyTrain.py in examples/CartPole I get the error:
```
ModuleNotFoundError: No module named 'garage.baselines'
```
The baselines folder to which this is referring I think has been moved to garage/tf/baselines, but there isn't a linear_feature_baseline.py in garage/tf/baselines anymore

**Comment by mark-koren** [comment]
We use version [2019.10.1](https://github.com/rlworkgroup/garage/tree/v2019.10.1) for now, though we may try to update to the new 2020.06.X version soon. 

Let me know if that fixes the issue!
